version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.3
    # ports:
    # - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      #HASURA_GRAPHQL_ADMIN_SECRET: flutterando
      #HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "vdf0r8yt982erg8rt944rc23xfdfw34re23f23"}'
  auth-server:
    build: auth/.
    # ports:
    #   - "8081:8081"
    volumes:
      - "auth/.:/auth/"
    depends_on:
      - "postgres"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD:
      SIGNINGKEY: vdf0r8yt982erg8rt944rc23xfdfw34re23f23
  proxy:
    image: nginx:1.13
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - "auth-server"
    - "graphql-engine"
    ports:
      - 80:80
      - 443:443
  
volumes:
  db_data:
  auth:
  images:
